-- Migration: Add profile fields to users table
-- Date: 2025-01-01

ALTER TABLE users
  ADD COLUMN preferred_name VARCHAR(100) DEFAULT NULL,
  ADD COLUMN street1 VARCHAR(255) DEFAULT NULL,
  ADD COLUMN street2 VARCHAR(255) DEFAULT NULL,
  ADD COLUMN city VARCHAR(100) DEFAULT NULL,
  ADD COLUMN state VARCHAR(50) DEFAULT NULL,
  ADD COLUMN zip VARCHAR(20) DEFAULT NULL,
  ADD COLUMN phone VARCHAR(50) DEFAULT NULL,
  ADD COLUMN has_owned_a_dog TINYINT(1) DEFAULT NULL,
  ADD COLUMN has_children_at_home TINYINT(1) DEFAULT NULL,
  ADD COLUMN has_outdoor_space TINYINT(1) DEFAULT NULL;
